name: "Amye's Test 1"
favicon: null
layout_spectrum: 0.9052000793162733
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060701'
    - '#536a00'
    - '#819523'
    - '#cfb768'
  brandStrength: 0.375
  lightness: 0.6875
  saturation: 0.8703087472822517
  rhythmicContrast: 0.5
purpose: []
